### ISSUE TITLE
Fuck you Zclassic! Fix the God Damn wallets!

### ISSUE THREAD

**Issue by scorp22** [z-classic/electrum-zcl#126]

**Comment by tester2011** [comment]
A little harsh, but I understand the sentiment. 

A lot of people have considerable investments in ZCL and the wallet side of things is far from ideal.

Mike.

**Comment by scorp22** [comment]
Shit man if thats what a guy has to do to get someones attention I'll start swearing like a sailor. If you are a part of the team at zclassic you tell those guys to get that wallet fixed right now! Everybody is down 1000s of dollars on this. If you cant sent to wallet to get the btcp, then what the fuck man. this is a fucking scam. Ill go to san fran my self and hunt rhet and the team down. This isn't over mattress man.

**Comment by idbeentaken** [comment]
These guys are shameless

**Comment by satoshisirloin** [comment]
I read on the bctp.org website that you can go to tradesatoshi.com and create a free user, and under "balance" --> "search" type zclassic and next to the "zcl" initials there is a menu where you can choose create adress. The adress will be a long combination of letters. Then just go to where you have your coins and send them to your adress. There you you will receive your BTCP in three/four days.
I did this because my wallet does not work either. Or else i would have used the wallet.

**Comment by miyagison99** [comment]
I lost 27 ZCL in this wallet fuck up....what a scam its sad

**Comment by miyagison99** [comment]
all servers are down? perfect? ill stay positive, please fix this

**Comment by ob7** [comment]
sometimes you learn your lessons the hard way

**Comment by sulmone** [comment]
What is your issue?  We had over 20k concurrent users today and have been dealing with some scaling issues.  Have you tried the new 1.0.4 wallet?
