### ISSUE TITLE
2FA Wallet - Send Transaction isn't working

### ISSUE THREAD

**Issue by jagasuji** [z-classic/electrum-zcl#44]
Tried to send funds from Electrum wallet Z!1.0.0 to Bittrex wallet by entering ZCL address with various options of fees. But nothing happens when I click preview or send buttons. Restarted the wallet quite a few times but nothing helped.

**Comment by ch4ot1c** [comment]
Which platform? Did you import a private key or make a new standard wallet?

**Comment by jagasuji** [comment]
Windows 10. Created a new wallet with 2fa.

**Comment by ch4ot1c** [comment]
Will test this ASAP, thank you for letting us know. As long you have access to your private keys, your funds are safe.

**Comment by jagasuji** [comment]
Sure, thanks.

**Comment by ronstoppable87** [comment]
Hi,

I am having the same problems, I was wondering if it had anything to do with the 2FA. I have that enabled as well during the initial installation. After closing and re-opening the electrum file it does not ask me anything about a 2FA.

I have not tested creating another wallet without 2FA, I might try that tomorrow.

If this does not help, just ignore the message lol.

**Comment by imthiassi** [comment]
Hi,
Having the same issue here...nothing happens when pressing send or preview buttons.
windows 10.  new wallet with 2FA

**Comment by Yasu12345** [comment]
Same here. Windows 10, new wallet with 2FA.
Was able to send to my wallet just fine, but could not send it back.

**Comment by stevenbutler1** [comment]
Same here, windows 10, new computer, new wallet, 2FA , also showing transaction not verified after 43 confirmations

**Comment by stevenbutler1** [comment]
Tried recovering wallet with seed, transaction  now confirmed , still not working, press review or send buttons and nothing happens, using mcafee antivirus and firewall on if that makes any difference? Otherwise same as others running windows 10, 2FA

**Comment by Darren2607** [comment]
Same issue. Installed wallet on windows 10. Enabled 2fa.Transferred zcl there ,can't transfer it from wallet. Preview and send buttons don't work. 2fa hasn't appeared

**Comment by Thoth123456** [comment]
Same issue, also windows 10, 2FA etc. 

Did not see this issue and opened new one :( 

ZCL amount now blocked...

**Comment by ch4ot1c** [comment]
### Developer's Linux guide to retrieving funds from 2FA
#### See next post for the Windows instructions!

Alright, building a multisig transaction is how we'll get your funds out of this state. Fear not, it is a 2 / 3 multi-sig, and you have 2 of the xprvs (and the one xpub).

**Please make a backup copy of `~/.electrum-zcl/` before getting started.**

**Make sure you have the seed words you've made written down.**

If you can build using the Linux/Mac Development Instructions (from the Readme), you can retrieve your funds via the following steps. For everyone else (Windows), check out the post below.

**What Happened? (slightly technical) -**
You need your 2 xprvs and 1 xpub to sign for these addresses you saw / sent funds to. 2FA wallets are simple a 2/3 multi-sig, so that's what we'll set up to recover. The problem that occurred was a failure to hit the HTTP endpoint and get a 3rd xprv from the TrustedCoin 2FA service - but that's ok. The corresponding xpub we will use is 'deterministically' generated against your other keys, coming from a hard-coded value in the code - this is now all the supplies we'll need.

**These are in your `~/.electrum-zcl/wallets/` files; you can find them with command+f.**

For the adventurous / debugger, here is exactly where it happens in the code:

### Here's how to dump these:

**Be sure you have checked out v1.0.0:** https://github.com/BTCP-community/electrum-zcl/commit/30da9e6b20927baa7e15391e45815c24b534ec39

Backup (copy to a new folder): `~/.electrum-zcl`
And then delete it, so we can start a fresh wallet.

From version 1.0.0, in file `plugins/trustedcoin/trustedcoin.py`

Below the line saying:
```xprv2, xpub2 = self.get_xkeys(seed, passphrase, "m/1'/")```

Add:
```
print(str(xprv1))
print(str(xprv2))
```
And below:
```
xpub3 = make_xpub(signing_xpub, long_user_id)
```

Add: 
```
print(str(xpub3))
```
Then `python3 setup.py install`, and run. 

First, try to 'Restore 2FA wallet from seed words'; this will output (to terminal) the 2 xprvs and 1 xpub. 

Then, delete `~/.electrum-zcl` again, select 'Multi-sig wallet' this time, and select '2 cosigners, 3 total'. Paste the first xprv, then the next xprv, and then the xpub.

You should now be in your wallet with the same addresses as were in the seed words from your original 2FA setup attempt. Check your addresses, and send a quick test transaction to make sure everything worked. We have disabled 2FA wallets in the latest version, but you're in a Multisig wallet now regardless.

**Comment by ch4ot1c** [comment]
## Windows Guide to Retrieving ZCL from a 2FA Electrum Wallet

Have you accidentally set up your wallet as a 2FA wallet and now are unable to send coins else where? Has sweeping/ importing your private key not worked for you? As long as you sent the coins as a Transparent (T) address, this is the guide for you! If you used a Private (Z) address, follow up to step 4 and hang tight for when we release Electrum support for Private (Z) addresses.

1.    Create a new standard wallet and restore the 2FA wallet using your "seed" codes. DO NOT password protect this wallet.
2.    Disable the 2FA feature when presented with the option.
3.    Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open the new standard wallet file with Notepad.
4.    You will need to gather the 2 private keys and one public key. To find this easily, press “CTRL+F” and search for “xprv”. Copy the 2 “xprv” values as well as the last “xpub” value. You will need these in a later step.
5.    Create a new “Multi-signature wallet”. Select “From 3 co-signers” on the first slider. Select “Require 2 signatures” on the second slider.
6.    To add the first co-signer, click “Use public or private keys”. Enter the first xprv key in this box.
7.    Add the second co-signer via a private key also. 
8.    Add the third co-signer with the public key. Complete the set-up.
9.    Your wallet funds now have the ability to be sent from the multi-signature wallet. 

Credit to Entropyless and daniel12 on Discord

**Comment by dStorm-x58** [comment]
Thanks for the reply.  Just to clarify, per the last statement by ch4ot1c, (my situation) I sent funds to the new zcl-electrum 2fa Windows wallet from a zclassic Windows swing wallet Private address, Should I still try to complete with these instructions or per ch4ot1c's suggestion, 'wait for support for private addresses'.

**Comment by Thoth123456** [comment]
Thank you @ch4ot1c , your guides works perfectly :)

**Comment by ronstoppable87** [comment]
@ch4ot1c it worked!! 

send works flawlessly, daniel12 on discord deserves a huge thank you!

**Comment by Darren2607** [comment]
How do I know if I setup a transparent or private address? I can't remember

**Comment by tuday2** [comment]
Thank you  @ch4ot1c  , you got me out of the 2fa trap... super helpful!

**Comment by stevenbutler1** [comment]
Thanks @ch4ot1c<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fch4ot1c&data=02%7C01%7C%7Cab9ad8d63b7b4f039b5408d567d4fd30%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636529086827299559&sdata=femQK9V1%2FPcVHqwFiRmNlzycwdZjhviBmEycNRWKipg%3D&reserved=0>

I had already realised my mistake and re seeded the wallet to get my funds, I guess I should of read the post properly first, as you said it works fine without 2FA,

Going to cold storage my wallet anyway so no need for 2FA,

Regards,

Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FrankAllotta** [comment]
I'm not even using 2FA and my wallet looks the same.  I see transactions but they are at 0.00. Just using the addresses that were generated using the seed phrase, which are transparent.

**Comment by dStorm-x58** [comment]
@ch4ot1c was helping me because that was my problem, Tx = 1 Value = 0.00.  How do you know how much ZCL you have in those addresses?  Can you send ZCL from them?

**Comment by ch4ot1c** [comment]
If you sent funds from a Z address, they may not be visible yet. Keep hold of those seed words; I will update this post when the feature comes. This is a 1-2 week timeframe.

Thank you for your patience 👍

**Comment by FrankAllotta** [comment]
Well, that really would be the question.  I'm just receiving funds from a mining pool to the address I created with the Electrum wallet, so I don't know what address they are using. Could be the reason though. And by Z address, do you mean an address that starts with a "Z" or "z"? Not 100% sure I'm following you there.

**Comment by ch4ot1c** [comment]
Yes, that is very possible - please read: https://bitcoin.stackexchange.com/questions/49115/whats-the-difference-between-z-addr-and-t-addr-type-addresses

**Comment by FrankAllotta** [comment]
Yep, that has to be it.  When I view it on the blockchain explorer it shows No inputs.  That would tell me the address is a Z address sending to me.  Thanks Jon! I'll be patient. :)

**Comment by sulmone** [comment]
Try the new [release](https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3)
