### ISSUE TITLE
Cant withdraw/send from electrum (2fa)

### ISSUE THREAD

**Issue by Fanxd123** [z-classic/electrum-zcl#90]
Hello .
Icant seem to wthdraw my fund from my eceltrum nor send them anywere, is it due to med having 2FA turned on ? and if so, is there anything i can do to fix it ? 
thank you

**Comment by ch4ot1c** [comment]
It is indeed because of 2FA being on. It has since been disabled. Please see https://github.com/BTCP-community/electrum-zcl/issues/44 for instructions to get your funds.

Try this and let us know how it goes - sorry for the trouble!

(And, once this has worked for you, be sure to update to the latest version in Releases)
